name: Build Docker Image For Architecture

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: "The ref to build the image from. (usually this is a release tag, e.g. v4.0.1)"
      architecture:
        type: string
        required: true
      runner:
        type: string
        required: true
      imageTag:
        type: string
        required: true
        description: "The tag for the docker image. (usually a version tag without leading 'v')"
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false

jobs:
  build-docker-image:
    name: Build Docker Image for ${{ inputs.imageTag }} for Architecture ${{ inputs.architecture }}
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BOT_PAT }}
          ref: ${{ inputs.ref }}

      - name: Configure platform
        id: configure-platform
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            return "linux/${{ inputs.architecture }}";

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Publish Docker Image @:latest and @:v_._._
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          PLATFORM: ${{ fromJson(steps.configure-platform.outputs.result) }}
        run: |
          # compose image ID and change all uppercase to lowercase
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # get version and strip v from the front
          VERSION=${{ inputs.imageTag }}

          if [[ -z "$FONTAWESOME_NPM_AUTH_TOKEN" ]] ; \
            then docker buildx build . \
                  --file Dockerfile \
                  --tag $IMAGE_ID:latest \
                  --tag $IMAGE_ID:$VERSION \
                  --platform $PLATFORM \
                  --push ; \
            else docker buildx build . \
                  --file Dockerfile \
                  --tag $IMAGE_ID:latest \
                  --tag $IMAGE_ID:$VERSION \
                  --secret id=fontawesome_token,env=FONTAWESOME_NPM_AUTH_TOKEN \
                  --platform $PLATFORM \
                  --push ; \
          fi
