name: Run Test Coverage
on:
  workflow_call:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: npm install

  test-coverage-pr:
    name: Create Test Coverage PR
    needs: install-dependencies
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: "Install Dependencies"
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: npm install
      - name: "Test"
        run: npx vitest --coverage.enabled true --coverage.reporter=json-summary || true
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pr
          path: coverage-pr
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

  test-coverage-main:
    name: Create Test Coverage Main
    needs: install-dependencies
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: "Install Dependencies"
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: npm install
      - name: "Test"
        run: npx vitest --coverage.enabled true --coverage.reporter=json-summary || true
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-main
          path: coverage-main
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

  report-coverage:
    needs: [test-coverage-pr, test-coverage-main]
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-pr
          path: coverage-pr
      - uses: actions/download-artifact@v4
        with:
          name: coverage-main
          path: coverage-main
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
