name: Create Pre-Release

on:
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  create-pre-release:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: "dev"

      - name: Build and Publish Docker Image @:latest and @:v_._._
        run: |
          # copose image ID and change all uppercase to lowercase
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # build docker image
          docker build . --file Dockerfile --tag $IMAGE_ID:next

          # log into docker registry
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # push images
          docker push $IMAGE_ID:next
