name: Synchronize Main Branch after a Hotfix Release

# After releasing a hotfix, the release branch needs to be synchronized with the main branch again. 
# Ohterwise, hotfixes would never appear on the main branch and could also cause unexpected merge conflicts for the next regular release
# We open a PR from main to a sync branch that is a clone of the release branch.

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true

jobs:
  create-sync-pr:
    name: Creates a PR from main into a sync branch
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          ref: "release"
      
      - name: Check Out .github Repository
        uses: actions/checkout@v3
        with:
            repository: "dot-base/.github"
            ref: "main"
            path: "actions-repo"
            token: ${{ secrets.GH_BOT_PAT }}

      - name: Get latest release
        id: get-latest-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = response.data;

            if (!release) throw new Error('Could not find latest release.');
            return release;

      - name: Create a branch for resolving merge conflicts
        id: create-conflict-branch
        env:
          VERSION_TAG: ${{ fromJson(steps.get-latest-release.outputs.result).tag_name }}
        run: |
          actions-repo/scripts/create-conflict-branch.sh 

      - name: Create Sync PR
        id: create-sync-pr-step
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_BOT_PAT }}
          source_branch: "main"
          destination_branch: ${{ steps.create-conflict-branch.outputs.BRANCH_NAME }}
          pr_title: "sync(hotfix): ${{ fromJson(steps.get-latest-release.outputs.result).tag_name }}"
          pr_body: "This resolves potential merge conflicts between the hotfix release ${{ fromJson(steps.get-latest-release.outputs.result).tag_name }} and the main branch."
          pr_reviewer: "dot-base/development"
          pr_assignee: ${{ secrets.GH_BOT_USER }}
          pr_milestone: "next"
