name: ✨ Create Release PR

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: The branch with the changes that shall be released.
        required: true
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Check Out .github Repository
        uses: actions/checkout@v3
        with:
            repository: "dot-base/.github"
            ref: "feat/add-package-json"
            path: "actions-repo"
            token: ${{ secrets.GH_BOT_PAT }}

      - name: Install conventional-changelog
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          npm i

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0                                  # keep all changes in changelog
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          config-file-path: "actions-repo/.github/changelog.config.js"

      - name: Create Release PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_BOT_PAT }}
          source_branch: ${{ inputs.branch }}
          destination_branch: "release"
          pr_title: "chore(release): ${{ steps.changelog.outputs.tag }}"
          pr_body: "${{ steps.changelog.outputs.clean_changelog }}"
          pr_reviewer: "dot-base/development"
          pr_assignee: ${{ secrets.GH_BOT_USER }}
          pr_milestone: "next"
