name: ✨ Create Release PR

on:
  workflow_call:
    secrets:
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          ref: "dev"

      - name: Install conventional-changelog
        run: |
          npm i conventional-changelog-conventionalcommits

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0                                  # keep all changes in changelog
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          config-file-path: ".github/changelog.config.js"

      - name: Create Release PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_BOT_PAT }}
          source_branch: "dev"
          pr_title: "chore(release): ${{ steps.changelog.outputs.tag }}"
          pr_body: "${{ steps.changelog.outputs.clean_changelog }}"
          pr_reviewer: "dot-base/development"
          pr_assignee: ${{ secrets.GH_BOT_USER }}
          pr_milestone: "next"
