name: Create Pre-Release

on:
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  create-pre-release:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Publish Docker Image @:next
        run: |
          # copose image ID and change all uppercase to lowercase
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # log into docker registry
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # build docker images and push to registry
          docker buildx build . \
            --file Dockerfile \
            --tag $IMAGE_ID:next \
            --platform linux/amd64 \
            --push
