name: Create Release

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true        
      CR_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false
    inputs:
      isHotfixRelease:
        type: string
        required: true
    outputs:
      tag:
        description: "The semantic version tag generated for the created release e.g. v1.2.3"
        value: ${{ jobs.create-release.outputs.tag }}
      imageTag:
        description: "The Docker image tag corresponding to a release tag. This is without a leading 'v'!"
        value: ${{ jobs.create-release.outputs.imageTag }}

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      imageTag: ${{ steps.strip-leading-v.outputs.imageTag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BOT_PAT }}
          ref: "release"

      - name: Check Out .github Repository
        uses: actions/checkout@v3
        with:
            repository: "dot-base/.github"
            ref: "main"
            path: "actions-repo"
            token: ${{ secrets.GH_BOT_PAT }}

      - name: Install conventional-changelog
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: |
          npm i conventional-changelog-conventionalcommits

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0 # keep all changes in changelog
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          config-file-path: "actions-repo/.github/changelog.config.js"

      - name: Strip Leading 'v'
        id: strip-leading-v
        run:
          # get version and strip v from the front
          VERSION=${{ steps.changelog.outputs.tag }}
          echo "imageTag=$(echo $VERSION | sed -e 's/^v//')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
        with:
          commitish: "release"
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Fast Forward main to release
        if: inputs.isHotfixRelease == 'true'
        run: |
          git reset --hard
          git checkout main
          git merge --ff-only origin/release
          git push

      - name: Manage Milestones
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            // get next milestone
            const milestones = await github.paginate('GET /repos/{owner}/{repo}/milestones', {
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const currentMilestone = milestones.find((m) => m.title === 'next');

            // update current next milestone to released version
            if(currentMilestone) {
              console.log('Renaming and closing current milestone');
              await github.request('PATCH /repos/{owner}/{repo}/milestones/{milestone_number}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone_number: currentMilestone.number,
                title: '${{ steps.changelog.outputs.tag }}',
                state: 'closed'
              });
            }

            // create new next milestone
            console.log('Opening new "next" milestone');
            const nextMilestone  = await github.request('POST /repos/{owner}/{repo}/milestones', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'next'
            });

            // fetch open PRs to to set new "next" milestone
            console.log('Set milestone of open PRs to new "next"');
            const pulls = await github.paginate('GET /repos/{owner}/{repo}/pulls?state=open', {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // set milestone of open PRs to new "next"
            for (const pull of pulls) {
              await github.request('PATCH /repos/{owner}/{repo}/issues/{pull_request_number}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_request_number: pull.number,
                milestone: nextMilestone.data.number
              });
            }
