name: Manage PR

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false
    inputs:
      RUN_COVERAGE:
        required: false
        type: string
        default: "false"

jobs:
  lint-and-test:
    name: Lint Files and Run Tests
    uses: dot-base/.github/.github/workflows/lint-and-test.yml@main
    secrets:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
    with:
      RUN_COVERAGE: ${{ inputs.RUN_COVERAGE }}

  get-pr:
    name: Get PR
    needs: lint-and-test
    uses: dot-base/.github/.github/workflows/get-pr.yml@main
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}

  lint-pr-title:
    name: Lint PR Title
    needs: get-pr
    uses: dot-base/.github/.github/workflows/lint-pr-title.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}

  merge-release-pr:
    name: Merge Release PR
    needs: [get-pr, lint-pr-title]
    if: ${{ fromJson(needs.get-pr.outputs.pr).type == 'release' && fromJson(needs.get-pr.outputs.pr).isMergeable == true }}
    uses: dot-base/.github/.github/workflows/merge-release-pr.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

  configure-manually-opened-feature-pr:
    name: Configure Manually Opened Feature PR
    needs: [get-pr, lint-pr-title]
    if: ${{ fromJson(needs.get-pr.outputs.pr).type == 'feature' }}
    uses: dot-base/.github/.github/workflows/configure-manually-opened-feature-pr.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}

  merge-sync-pr:
    name: Merge Sync PR
    needs: [get-pr, lint-pr-title]
    if: ${{ fromJson(needs.get-pr.outputs.pr).type == 'sync' && fromJson(needs.get-pr.outputs.pr).isMergeable == true }}
    uses: dot-base/.github/.github/workflows/merge-sync-pr.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
