name: Merge Release PR

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
    inputs:
      pr:
        required: true
        type: string

jobs:
  merge-release-pr:
    name: Merge Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge Release PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            const pr = ${{ inputs.pr }};
            try {
              console.log(`Trying to merge PR ${pr.number}.`);
              const mergeResponse = await github.request("PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge", { 
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: pr.title,
                commit_message: pr.body,
                merge_method: "merge"
              });
              console.log(`PR ${pr.number} has been merged.`);
            } catch (e) {
              const errorMessage = `PR ${pr.number} is not mergeable: ${e.message}`;
              console.error(errorMessage);
              throw new Error(errorMessage);
            }

  run-sync-main-and-release-branch:
    name: Synchronize Release Branch and Main Branch
    needs: merge-release-pr
    if: ${{ fromJson(inputs.pr).type == 'release' && fromJson(inputs.pr).head.ref != 'main' }}
    uses: .github/workflows/synchronize-main-and-release-branch.yml@main
    with:
      pr: ${{ inputs.pr }}
      tag: ${{ inputs.pr.tag }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}