name: Merge Feature PR

on:
  workflow_call:
    secrets:
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true
    inputs:
      pr:
        required: true
        type: string

jobs:
  merge-feature-pr:
    name: Merge Feature PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge Feature PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            const pr = ${{ inputs.pr }};
            try {
              console.log(`Trying to merge PR ${pr.number}.`);
              const mergeResponse = await github.request("PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge", { 
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: pr.title,
                commit_message: pr.body,
                merge_method: "squash"
              });
              console.log(`PR ${pr.number} has been merged.`);
            } catch (e) {
              console.error(`PR ${pr.number} is not mergeable: ${e.message}`)
            }
