name: Merge Release PR

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: true
      
    inputs:
      pr:
        required: true
        type: string

jobs:
  merge-release-pr:
    name: Merge Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Merge Release PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            const pr = ${{ inputs.pr }};
            try {
              console.log(`Trying to merge PR ${pr.number}.`);
              const mergeResponse = await github.request("PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge", { 
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                commit_title: pr.title,
                commit_message: pr.body,
                merge_method: "merge"
              });
              console.log(`PR ${pr.number} has been merged.`);
            } catch (e) {
              const errorMessage = `PR ${pr.number} is not mergeable: ${e.message}`;
              console.error(errorMessage);
              throw new Error(errorMessage);
            }

  create-release:
    name: Create Release
    needs: merge-release-pr
    uses: dot-base/.github/.github/workflows/create-release.yml@main
    with:
      isHotfixRelease: ${{ fromJson(inputs.pr).type == 'release' && fromJson(inputs.pr).head.ref != 'main' }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

  run-sync-main-and-release-branch:
    name: Synchronize Release Branch and Main Branch
    needs: create-release
    if: fromJson(inputs.pr).type == 'release' && fromJson(inputs.pr).head.ref != 'main'
    uses: dot-base/.github/.github/workflows/synchronize-main-and-release-branch.yml@main
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}tag

  build-docker-image:
    name: Build a Docker image for a new release
    needs: create-release
    uses: dot-base/.github/.github/workflows/build-docker-image-manually.yml@main
    with:
      architecture: both
      imageTag: ${{ needs.create-release.outputs.imageTag }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}