name: Standalone Merge Release PR

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      CR_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false
    inputs:
      pr_number:
        type: string
      SERVICE_TYPE:
        required: true
        type: string

jobs:
  get-pr:
    name: Get PR
    uses: dot-base/.github/.github/workflows/get-pr.yml@main
    with:
      pr_number: ${{ inputs.pr_number }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}

  lint-pr-title:
    name: Lint PR Title
    needs: get-pr
    uses: dot-base/.github/.github/workflows/lint-pr-title.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}

  merge-release-pr:
    name: Merge Release PR
    needs: [get-pr, lint-pr-title]
    if: fromJson(needs.get-pr.outputs.pr).type == 'release'
    uses: dot-base/.github/.github/workflows/merge-release-pr.yml@main
    with:
      pr: ${{ needs.get-pr.outputs.pr }}
      SERVICE_TYPE: ${{ inputs.SERVICE_TYPE }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
