name: Merge Sync PR

on:
    workflow_call:
        secrets:
            GH_BOT_USER:
                required: true
            GH_BOT_PAT:
                required: true
        inputs:
            pr:
                required: true
                type: string

jobs:
    merge-sync-pr:
        name: Merge Sync PR
        runs-on: ubuntu-latest
        steps:
        - name: Merge Sync PR
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GH_BOT_PAT }}
            script: |
                const pr = ${{ inputs.pr }};
                try {
                console.log(`Trying to merge PR ${pr.number}.`);
                const mergeResponse = await github.request("PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge", { 
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    commit_title: pr.title,
                    commit_message: pr.body,
                    merge_method: "merge"
                });
                console.log(`PR ${pr.number} has been merged.`);
                } catch (e) {
                const errorMessage = `PR ${pr.number} is not mergeable: ${e.message}`;
                console.error(errorMessage);
                throw new Error(errorMessage);
                }

    update-main:
        name: Update 'main' branch with sync commit
        runs-on: ubuntu-latest
        needs: merge-sync-pr
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GH_BOT_PAT }}
                ref: release
            - name: Check Out .github Repository
              uses: actions/checkout@v3
              with:
                repository: "dot-base/.github"
                ref: "main"
                path: "actions-repo"
                token: ${{ secrets.GH_BOT_PAT }}
            - name: Fast Forward main to sync branch
              env:
                BRANCH_NAME: ${{ fromJSON(inputs.pr).base.ref }}
                DELETE_BRANCH: "true"
              run: |
                actions-repo/scripts/fast-forward-main.sh
