name: PR Checks
# This workflow is the new generation of PR checks and can eventually replace 'Manage PR'.

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false
    inputs:
      RUN_COVERAGE:
        required: false
        type: string
        default: "false"
      RUN_TYPECHECK:
        required: false
        type: string
        default: "false"
      SERVICE_TYPE:
        type: string
        default: "node"
      JAVA_VERSION:
        type: number

jobs:
  code-check:
    name: Run code checks
    uses: dot-base/.github/.github/workflows/code-check.yml@main
    secrets:
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    with:
      RUN_COVERAGE: ${{ inputs.RUN_COVERAGE }}
      RUN_TYPECHECK: ${{ inputs.RUN_TYPECHECK }}
      SERVICE_TYPE: ${{ inputs.SERVICE_TYPE }}
      JAVA_VERSION: ${{ inputs.JAVA_VERSION }}

  lint-pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Verify Compliance with Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
        with:
          types: |
            feat
            fix
            chore
          requireScope: false

