name: Synchronize Release Branch and Main Branch after a Hotfix Release

# After releasing a hotfix, the release branch needs to be synchronized with the main branch again. 
# Ohterwise, hotfixes would never appear on the main branch and could also cause unexpected merge conflicts for the next regular release
# If there are no merge conflicts between release and main, we automatically merge release into main.
# If merge conflicts appear, this action only opens a PR on main.

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true
    inputs:
      hotfix-tag:
        required: true
        type: string

jobs:

  create-synchronize-pr:
    name: Creates a PR from release branch to main branch
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          ref: "release"
      
      - name: Check Out .github Repository
        uses: actions/checkout@v3
        with:
            repository: "dot-base/.github"
            ref: "main"
            path: "actions-repo"
            token: ${{ secrets.GH_BOT_PAT }}

      - name: Install conventional-changelog
        run: |
          npm i conventional-changelog-conventionalcommits

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0                                  # keep all changes in changelog
          output-file: "false"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          config-file-path: "actions-repo/.github/changelog.config.js"

      - name: Create Sync PR
        id: create-sync-pr-step
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_BOT_PAT }}
          source_branch: "release"
          destination_branch: "main"
          pr_title: "sync(hotfix): ${{ inputs.tag }}"
          pr_body: "${{ steps.changelog.outputs.clean_changelog }}"
          pr_reviewer: "dot-base/development"
          pr_assignee: ${{ secrets.GH_BOT_USER }}
          pr_milestone: ${{ inputs.hotfix-tag }}

