name: Synchronize Release Branch and Main Branch after a Hotfix Release

# After releasing a hotfix, the release branch needs to be synchronized with the main branch again. 
# Ohterwise, hotfixes would never appear on the main branch and could also cause unexpected merge conflicts for the next regular release
# If there are no merge conflicts between release and main, we automatically merge release into main.
# If merge conflicts appear, this action only opens a PR on main.

on:
  workflow_call:
    secrets:
      GH_BOT_USER:
        required: true
      GH_BOT_PAT:
        required: true

jobs:
  create-synchronize-pr:
    name: Creates a PR from release branch to main branch
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          ref: "release"
      
      - name: Check Out .github Repository
        uses: actions/checkout@v3
        with:
            repository: "dot-base/.github"
            ref: "main"
            path: "actions-repo"
            token: ${{ secrets.GH_BOT_PAT }}

      - name: Get latest release
        id: get-latest-release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_BOT_PAT }}
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = response.data;

            if (!release) throw new Error('Could not find latest release.');
            return release;

      - name: Create a branch for resolving merge conflicts
        id: create-conflict-branch
        env:
          BRANCH_NAME: sync/${{ fromJson(steps.get-latest-release.outputs.result).tag_name }}
        run: |
          git reset --hard
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Sync PR
        id: create-sync-pr-step
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_BOT_PAT }}
          source_branch: ${{ steps.create-conflict-branch.outputs.BRANCH_NAME }}
          destination_branch: "main"
          pr_title: "sync(hotfix): ${{ fromJson(steps.get-latest-release.outputs.result).tag_name }}"
          pr_body: "${{ fromJson(steps.get-latest-release.outputs.result).body }}"
          pr_reviewer: "dot-base/development"
          pr_assignee: ${{ secrets.GH_BOT_USER }}
          pr_milestone: "next"
